
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: your mosquitto address
  port: your mosquitto port
  username: your mosquitto auth id
  password: your mosquitto auth password

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: warning

light:
  - platform: mqtt
    name: "거실 천장 1"
    unique_id: "livingroomlight1"
    schema: template
    state_topic: "home/state/light/1/0"
    command_topic: "home/command/light/1/0"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "거실 천장 2"
    unique_id: "livingroomlight2"
    schema: template
    state_topic: "home/state/light/1/1"
    command_topic: "home/command/light/1/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "복도 천장"
    unique_id: "hallwaylight"
    schema: template
    state_topic: "home/state/light/1/2"
    command_topic: "home/command/light/1/2"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "침실 천장"
    unique_id: "bedroomlight"
    schema: template
    state_topic: "home/state/light/2/0"
    command_topic: "home/command/light/2/0"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "실외기실 천장"
    unique_id: "outdoorunitlight"
    schema: template
    state_topic: "home/state/light/2/1"
    command_topic: "home/command/light/2/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "서재 천장"
    unique_id: "librarylight"
    schema: template
    state_topic: "home/state/light/3/1"
    command_topic: "home/state/light/3/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "컴퓨터방 천장"
    unique_id: "pcroomlight"
    schema: template
    state_topic: "home/state/light/4/0"
    command_topic: "home/command/light/4/0"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "식탁 천장"
    unique_id: "tablelight"
    schema: template
    state_topic: "home/state/light/6/0"
    command_topic: "home/command/light/6/0"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "조리대 천장"
    unique_id: "countertoplight"
    schema: template
    state_topic: "home/state/light/6/1"
    command_topic: "home/command/light/6/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false

switch:
  - platform: mqtt
    name: "거실 콘센트 1"
    unique_id: "livingroom_outlet_1"
    state_topic: "home/state/outlet/1/0"
    command_topic: "home/command/outlet/1/0"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "거실 콘센트 2"
    unique_id: "livingroom_outlet_2"
    state_topic: "home/state/outlet/1/1"
    command_topic: "home/command/outlet/1/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "침실 콘센트 1"
    unique_id: "bedroom_outlet_1"
    state_topic: "home/state/outlet/2/0"
    command_topic: "home/command/outlet/2/0"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "침실 콘센트 2"
    unique_id: "bedroom_outlet_2"
    state_topic: "home/state/outlet/2/1"
    command_topic: "home/command/outlet/2/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "서재 콘센트 1"
    unique_id: "library_outlet_1"
    state_topic: "home/state/outlet/3/0"
    command_topic: "home/command/outlet/3/0"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "서재 콘센트 2"
    unique_id: "library_outlet_2"
    state_topic: "home/state/outlet/3/1"
    command_topic: "home/command/outlet/3/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "컴퓨터방 콘센트 1"
    unique_id: "pcroom_outlet_1"
    state_topic: "home/state/outlet/4/0"
    command_topic: "home/command/outlet/4/0"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "컴퓨터방 콘센트 2"
    unique_id: "pcroom_outlet_2"
    state_topic: "home/state/outlet/4/1"
    command_topic: "home/command/outlet/4/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "주방 콘센트 1"
    unique_id: "kitchen_outlet_1"
    state_topic: "home/state/outlet/6/0"
    command_topic: "home/command/outlet/6/0"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "주방 콘센트 2"
    unique_id: "kitchen_outlet_2"
    state_topic: "home/state/outlet/6/1"
    command_topic: "home/command/outlet/6/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "가스 밸브"
    unique_id: "kitchengasvalve"
    state_topic: "home/state/gasvalve/0/0"
    command_topic: "home/command/gasvalve/0/0"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:pipe-valve
  - platform: mqtt
    name: "엘리베이터 호출"
    unique_id: "elevator_call"
    state_topic: "home/state/elevator/0/0"
    command_topic: "home/command/elevator/0/0"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 6 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:elevator

climate:
  - platform: mqtt
    name: "거실 난방"
    unique_id: "livingroom_thermostat"
    modes:
      - "off"
      - "heat"
    mode_state_topic: "home/state/thermostat/1/0"
    mode_state_template: "{{ value_json.state.lower() }}"
    mode_command_topic: "home/command/thermostat/1/0"
    mode_command_template: >-
      {% set values = {'off': '"OFF"', 'heat': '"HEAT"'} %}
      { "state": {{ values[value] if value in values.keys() else "OFF" }} }
    temperature_state_topic: "home/state/thermostat/1/0"
    temperature_state_template: "{{ value_json.targetTemperature }}"
    temperature_command_topic: "home/command/thermostat/1/0"
    temperature_command_template: '{ "targetTemperature": {{ value }} }'
    current_temperature_topic: "home/state/thermostat/1/0"
    current_temperature_template: "{{ value_json.currentTemperature }}"
    min_temp: 18
    max_temp: 30
    precision: 1
  - platform: mqtt
    name: "침실 난방"
    unique_id: "bedroom_thermostat"
    modes:
      - "off"
      - "heat"
    mode_state_topic: "home/state/thermostat/2/0"
    mode_state_template: "{{ value_json.state.lower() }}"
    mode_command_topic: "home/command/thermostat/2/0"
    mode_command_template: >-
      {% set values = {'off': '"OFF"', 'heat': '"HEAT"'} %}
      { "state": {{ values[value] if value in values.keys() else "OFF" }} }
    temperature_state_topic: "home/state/thermostat/2/0"
    temperature_state_template: "{{ value_json.targetTemperature }}"
    temperature_command_topic: "home/command/thermostat/2/0"
    temperature_command_template: '{ "targetTemperature": {{ value }} }'
    current_temperature_topic: "home/state/thermostat/2/0"
    current_temperature_template: "{{ value_json.currentTemperature }}"
    min_temp: 18
    max_temp: 30
    precision: 1
  - platform: mqtt
    name: "서재 난방"
    unique_id: "library_thermostat"
    modes:
      - "off"
      - "heat"
    mode_state_topic: "home/state/thermostat/3/0"
    mode_state_template: "{{ value_json.state.lower() }}"
    mode_command_topic: "home/command/thermostat/3/0"
    mode_command_template: >-
      {% set values = {'off': '"OFF"', 'heat': '"HEAT"'} %}
      { "state": {{ values[value] if value in values.keys() else "OFF" }} }
    temperature_state_topic: "home/state/thermostat/3/0"
    temperature_state_template: "{{ value_json.targetTemperature }}"
    temperature_command_topic: "home/command/thermostat/3/0"
    temperature_command_template: '{ "targetTemperature": {{ value }} }'
    current_temperature_topic: "home/state/thermostat/3/0"
    current_temperature_template: "{{ value_json.currentTemperature }}"
    min_temp: 18
    max_temp: 30
    precision: 1
  - platform: mqtt
    name: "컴퓨터방 난방"
    unique_id: "pcroom_thermostat"
    modes:
      - "off"
      - "heat"
    mode_state_topic: "home/state/thermostat/4/0"
    mode_state_template: "{{ value_json.state.lower() }}"
    mode_command_topic: "home/command/thermostat/4/0"
    mode_command_template: >-
      {% set values = {'off': '"OFF"', 'heat': '"HEAT"'} %}
      { "state": {{ values[value] if value in values.keys() else "OFF" }} }
    temperature_state_topic: "home/state/thermostat/4/0"
    temperature_state_template: "{{ value_json.targetTemperature }}"
    temperature_command_topic: "home/command/thermostat/4/0"
    temperature_command_template: '{ "targetTemperature": {{ value }} }'
    current_temperature_topic: "home/state/thermostat/4/0"
    current_temperature_template: "{{ value_json.currentTemperature }}"
    min_temp: 18
    max_temp: 30
    precision: 1
  - platform: mqtt
    name: "거실 에어컨"
    unique_id: "livingroom_airconditioner"
    modes:
      - "off"
      - "cool"
      - "auto"
      - "dry"
      - "fan_only"
    fan_modes:
      - "Max"
      - "Medium"
      - "Min"
      - "Auto"
    mode_state_topic: "home/state/airconditioner/1/0"
    mode_state_template: "{{ value_json.mode }}"
    mode_command_topic: "home/command/airconditioner/1/0"
    mode_command_template: >-
      {% set values = {"off": 0, "cool": 1, "auto": 2, "dry": 3, "fan_only": 4} %}
      { "mode": {{ values[value] if value in values.keys() else 0 }} }
    temperature_state_topic: "home/state/airconditioner/1/0"
    temperature_state_template: "{{ value_json.targetTemperature }}"
    temperature_command_topic: "home/command/airconditioner/1/0"
    temperature_command_template: '{ "targetTemperature": {{ value }} }'
    current_temperature_topic: "home/state/airconditioner/1/0"
    current_temperature_template: "{{ value_json.currentTemperature }}"
    fan_mode_command_topic: "home/command/airconditioner/1/0"
    fan_mode_command_template: '{ "rotationspeed_name": "{{ value }}" }'
    fan_mode_state_topic: "home/state/airconditioner/1/0"
    fan_mode_state_template: "{{ value_json.rotationspeed_name }}"
    min_temp: 18
    max_temp: 30
    precision: 1
  - platform: mqtt
    name: "침실 에어컨"
    unique_id: "bedroom_airconditioner"
    modes:
      - "off"
      - "cool"
      - "auto"
      - "dry"
      - "fan_only"
    fan_modes:
      - "Max"
      - "Medium"
      - "Min"
      - "Auto"
    mode_state_topic: "home/state/airconditioner/2/0"
    mode_state_template: "{{ value_json.mode }}"
    mode_command_topic: "home/command/airconditioner/2/0"
    mode_command_template: >-
      {% set values = {"off": 0, "cool": 1, "auto": 2, "dry": 3, "fan_only": 4} %}
      { "mode": {{ values[value] if value in values.keys() else 0 }} }
    temperature_state_topic: "home/state/airconditioner/2/0"
    temperature_state_template: "{{ value_json.targetTemperature }}"
    temperature_command_topic: "home/command/airconditioner/2/0"
    temperature_command_template: '{ "targetTemperature": {{ value }} }'
    current_temperature_topic: "home/state/airconditioner/2/0"
    current_temperature_template: "{{ value_json.currentTemperature }}"
    fan_mode_command_topic: "home/command/airconditioner/2/0"
    fan_mode_command_template: '{ "rotationspeed_name": "{{ value }}" }'
    fan_mode_state_topic: "home/state/airconditioner/2/0"
    fan_mode_state_template: "{{ value_json.rotationspeed_name }}"
    min_temp: 18
    max_temp: 30
    precision: 1
  - platform: mqtt
    name: "서재 에어컨"
    unique_id: "library_airconditioner"
    modes:
      - "off"
      - "cool"
      - "auto"
      - "dry"
      - "fan_only"
    fan_modes:
      - "Max"
      - "Medium"
      - "Min"
      - "Auto"
    mode_state_topic: "home/state/airconditioner/3/0"
    mode_state_template: "{{ value_json.mode }}"
    mode_command_topic: "home/command/airconditioner/3/0"
    mode_command_template: >-
      {% set values = {"off": 0, "cool": 1, "auto": 2, "dry": 3, "fan_only": 4} %}
      { "mode": {{ values[value] if value in values.keys() else 0 }} }
    temperature_state_topic: "home/state/airconditioner/3/0"
    temperature_state_template: "{{ value_json.targetTemperature }}"
    temperature_command_topic: "home/command/airconditioner/3/0"
    temperature_command_template: '{ "targetTemperature": {{ value }} }'
    current_temperature_topic: "home/state/airconditioner/3/0"
    current_temperature_template: "{{ value_json.currentTemperature }}"
    fan_mode_command_topic: "home/command/airconditioner/3/0"
    fan_mode_command_template: '{ "rotationspeed_name": "{{ value }}" }'
    fan_mode_state_topic: "home/state/airconditioner/3/0"
    fan_mode_state_template: "{{ value_json.rotationspeed_name }}"
    min_temp: 18
    max_temp: 30
    precision: 1
  - platform: mqtt
    name: "컴퓨터방 에어컨"
    unique_id: "pcroom_airconditioner"
    modes:
      - "off"
      - "cool"
      - "auto"
      - "dry"
      - "fan_only"
    fan_modes:
      - "Max"
      - "Medium"
      - "Min"
      - "Auto"
    mode_state_topic: "home/state/airconditioner/4/0"
    mode_state_template: "{{ value_json.mode }}"
    mode_command_topic: "home/command/airconditioner/4/0"
    mode_command_template: >-
      {% set values = {"off": 0, "cool": 1, "auto": 2, "dry": 3, "fan_only": 4} %}
      { "mode": {{ values[value] if value in values.keys() else 0 }} }
    temperature_state_topic: "home/state/airconditioner/4/0"
    temperature_state_template: "{{ value_json.targetTemperature }}"
    temperature_command_topic: "home/command/airconditioner/4/0"
    temperature_command_template: '{ "targetTemperature": {{ value }} }'
    current_temperature_topic: "home/state/airconditioner/4/0"
    current_temperature_template: "{{ value_json.currentTemperature }}"
    fan_mode_command_topic: "home/command/airconditioner/4/0"
    fan_mode_command_template: '{ "rotationspeed_name": "{{ value }}" }'
    fan_mode_state_topic: "home/state/airconditioner/4/0"
    fan_mode_state_template: "{{ value_json.rotationspeed_name }}"
    min_temp: 18
    max_temp: 30
    precision: 1

fan:
  - platform: mqtt
    name: "전열교환기"
    unique_id: "ventilator"
    state_topic: "home/state/ventilator/0/0"
    state_value_template: "{% if value_json.state %} ON {% else %} OFF {% endif %}"
    command_topic: "home/command/ventilator/0/0"
    command_template: >- 
      {% set values = {'OFF': 0, 'ON': 1} %}
      { "state": {{ values[value] if value in values.keys() else 0 }} }
    percentage_state_topic: "home/state/ventilator/0/0"
    percentage_value_template: "{{ value_json.rotationspeed }}"
    percentage_command_topic: "home/command/ventilator/0/0"
    percentage_command_template: '{ "rotationspeed": {{ value }} }'
    speed_range_min: 1
    speed_range_max: 100

lock:
  - platform: mqtt
    name: "현관 도어락"
    unique_id: "doorlock_frontdoor"
    state_topic: "home/state/doorlock/0/0"
    command_topic: "home/command/doorlock/0/0"
    value_template: '{{ value_json.doorlock_state }}'
    payload_lock: '{ "state": "Secured" }'
    payload_unlock: '{ "state": "Unsecured" }'
    state_locked: "Secured"
    state_unlocked: "Unsecured"
    optimistic: false
    retain: false
    icon: mdi:door-closed-lock

sensor:
  - platform: mqtt
    name: "엘리베이터 도착"
    unique_id: "elevator_arrived"
    state_topic: "home/state/elevator/0/0"
    value_template: >- 
      {% if value_json.state == 0 %}
      IDLE
      {% elif value_json.state == 1 %}
      ARRIVED
      {% else %}
      MOVING
      {% endif %}
    icon: mdi:elevator-passenger

http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem

google_assistant:
  project_id: your google assistant project id
  service_account: !include gcp_service_account.json
  report_state: true
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - sensor
    - fan
    - button
    - climate
    - binary sensor